import type { Asset } from '@/types';

// Seeded pseudo-random generator for deterministic data
function seededRandom(seed: number): () => number {
  let s = seed;
  return () => {
    s = (s * 9301 + 49297) % 233280;
    return s / 233280;
  };
}

function generateHistory(basePrice: number, seed: number, points = 30): number[] {
  const rng = seededRandom(seed);
  const history: number[] = [];
  let price = basePrice * (0.8 + rng() * 0.2);
  for (let i = 0; i < points; i++) {
    price *= 1 + (rng() - 0.48) * 0.06;
    history.push(Math.round(price * 100) / 100);
  }
  return history;
}

const STOCK_DATA: Array<[string, string, number, string]> = [
  ['AAPL', 'Apple Inc.', 229.0, 'Technology'],
  ['MSFT', 'Microsoft Corp.', 418.0, 'Technology'],
  ['NVDA', 'NVIDIA Corp.', 126.0, 'Technology'],
  ['GOOGL', 'Alphabet Inc.', 167.0, 'Technology'],
  ['AMZN', 'Amazon.com Inc.', 186.0, 'Consumer'],
  ['META', 'Meta Platforms', 515.0, 'Technology'],
  ['TSLA', 'Tesla Inc.', 248.0, 'Automotive'],
  ['BRK.B', 'Berkshire Hathaway', 445.0, 'Financial'],
  ['JPM', 'JPMorgan Chase', 210.0, 'Financial'],
  ['V', 'Visa Inc.', 275.0, 'Financial'],
  ['JNJ', 'Johnson & Johnson', 165.0, 'Healthcare'],
  ['WMT', 'Walmart Inc.', 78.0, 'Consumer'],
  ['XOM', 'Exxon Mobil', 118.0, 'Energy'],
  ['UNH', 'UnitedHealth Group', 510.0, 'Healthcare'],
  ['MA', 'Mastercard Inc.', 470.0, 'Financial'],
  ['PG', 'Procter & Gamble', 168.0, 'Consumer'],
  ['HD', 'Home Depot', 360.0, 'Consumer'],
  ['CVX', 'Chevron Corp.', 155.0, 'Energy'],
  ['ORCL', 'Oracle Corp.', 140.0, 'Technology'],
  ['ABBV', 'AbbVie Inc.', 195.0, 'Healthcare'],
  ['MRK', 'Merck & Co.', 102.0, 'Healthcare'],
  ['PEP', 'PepsiCo Inc.', 170.0, 'Consumer'],
  ['KO', 'Coca-Cola Co.', 63.0, 'Consumer'],
  ['AVGO', 'Broadcom Inc.', 165.0, 'Technology'],
  ['COST', 'Costco Wholesale', 875.0, 'Consumer'],
  ['BAC', 'Bank of America', 40.0, 'Financial'],
  ['MCD', "McDonald's Corp.", 295.0, 'Consumer'],
  ['CSCO', 'Cisco Systems', 48.0, 'Technology'],
  ['TMO', 'Thermo Fisher', 580.0, 'Healthcare'],
  ['ACN', 'Accenture plc', 345.0, 'Technology'],
  ['ABT', 'Abbott Laboratories', 112.0, 'Healthcare'],
  ['NFLX', 'Netflix Inc.', 690.0, 'Technology'],
  ['DHR', 'Danaher Corp.', 255.0, 'Healthcare'],
  ['LIN', 'Linde plc', 470.0, 'Materials'],
  ['TXN', 'Texas Instruments', 195.0, 'Technology'],
  ['WFC', 'Wells Fargo', 60.0, 'Financial'],
  ['PM', 'Philip Morris', 110.0, 'Consumer'],
  ['NEE', 'NextEra Energy', 82.0, 'Utilities'],
  ['UPS', 'United Parcel Service', 130.0, 'Industrial'],
  ['RTX', 'RTX Corp.', 120.0, 'Industrial'],
  ['HON', 'Honeywell International', 205.0, 'Industrial'],
  ['LOW', "Lowe's Companies", 255.0, 'Consumer'],
  ['BA', 'Boeing Co.', 175.0, 'Industrial'],
  ['INTU', 'Intuit Inc.', 640.0, 'Technology'],
  ['SBUX', 'Starbucks Corp.', 92.0, 'Consumer'],
  ['CAT', 'Caterpillar Inc.', 360.0, 'Industrial'],
  ['GS', 'Goldman Sachs', 470.0, 'Financial'],
  ['AMD', 'Advanced Micro Devices', 155.0, 'Technology'],
  ['IBM', 'IBM Corp.', 215.0, 'Technology'],
  ['GE', 'General Electric', 175.0, 'Industrial'],
  ['AMGN', 'Amgen Inc.', 230.0, 'Healthcare'],
  ['DE', 'Deere & Co.', 390.0, 'Industrial'],
  ['ISRG', 'Intuitive Surgical', 480.0, 'Healthcare'],
  ['AXP', 'American Express', 245.0, 'Financial'],
  ['BKNG', 'Booking Holdings', 4100.0, 'Consumer'],
  ['BLK', 'BlackRock Inc.', 920.0, 'Financial'],
  ['SYK', 'Stryker Corp.', 340.0, 'Healthcare'],
  ['ADI', 'Analog Devices', 225.0, 'Technology'],
  ['GILD', 'Gilead Sciences', 85.0, 'Healthcare'],
  ['PLD', 'Prologis Inc.', 120.0, 'Real Estate'],
  ['VRTX', 'Vertex Pharmaceuticals', 460.0, 'Healthcare'],
  ['TMUS', 'T-Mobile US', 200.0, 'Technology'],
  ['MMC', 'Marsh & McLennan', 220.0, 'Financial'],
  ['REGN', 'Regeneron Pharma', 930.0, 'Healthcare'],
  ['SCHW', 'Charles Schwab', 65.0, 'Financial'],
  ['ADP', 'Automatic Data Processing', 280.0, 'Technology'],
  ['LRCX', 'Lam Research', 72.0, 'Technology'],
  ['CI', 'Cigna Group', 350.0, 'Healthcare'],
  ['CB', 'Chubb Limited', 290.0, 'Financial'],
  ['MO', 'Altria Group', 52.0, 'Consumer'],
  ['BMY', 'Bristol-Myers Squibb', 50.0, 'Healthcare'],
  ['EQIX', 'Equinix Inc.', 810.0, 'Real Estate'],
  ['ICE', 'Intercontinental Exchange', 160.0, 'Financial'],
  ['SO', 'Southern Company', 85.0, 'Utilities'],
  ['DUK', 'Duke Energy', 115.0, 'Utilities'],
  ['ITW', 'Illinois Tool Works', 260.0, 'Industrial'],
  ['AON', 'Aon plc', 350.0, 'Financial'],
  ['CME', 'CME Group', 210.0, 'Financial'],
  ['CSX', 'CSX Corp.', 33.0, 'Industrial'],
  ['FDX', 'FedEx Corp.', 280.0, 'Industrial'],
  ['ZTS', 'Zoetis Inc.', 180.0, 'Healthcare'],
  ['BSX', 'Boston Scientific', 80.0, 'Healthcare'],
  ['TGT', 'Target Corp.', 145.0, 'Consumer'],
  ['MU', 'Micron Technology', 100.0, 'Technology'],
  ['MRVL', 'Marvell Technology', 80.0, 'Technology'],
  ['PANW', 'Palo Alto Networks', 360.0, 'Technology'],
  ['MCK', 'McKesson Corp.', 540.0, 'Healthcare'],
  ['ODFL', 'Old Dominion Freight', 215.0, 'Industrial'],
  ['EW', 'Edwards Lifesciences', 72.0, 'Healthcare'],
  ['KLAC', 'KLA Corp.', 750.0, 'Technology'],
  ['FCX', 'Freeport-McMoRan', 45.0, 'Materials'],
  ['NXPI', 'NXP Semiconductors', 210.0, 'Technology'],
  ['TJX', 'TJX Companies', 120.0, 'Consumer'],
  ['APH', 'Amphenol Corp.', 65.0, 'Technology'],
  ['EMR', 'Emerson Electric', 125.0, 'Industrial'],
  ['MCO', "Moody's Corp.", 460.0, 'Financial'],
  ['ROK', 'Rockwell Automation', 280.0, 'Industrial'],
  ['C', 'Citigroup Inc.', 60.0, 'Financial'],
  ['AIG', 'American International Group', 75.0, 'Financial'],
  ['MET', 'MetLife Inc.', 82.0, 'Financial'],
  ['PNC', 'PNC Financial', 195.0, 'Financial'],
  ['USB', 'US Bancorp', 48.0, 'Financial'],
  ['TFC', 'Truist Financial', 45.0, 'Financial'],
  ['COF', 'Capital One Financial', 175.0, 'Financial'],
  ['BK', 'Bank of New York Mellon', 72.0, 'Financial'],
  ['STT', 'State Street Corp.', 88.0, 'Financial'],
  ['PRU', 'Prudential Financial', 120.0, 'Financial'],
  ['AFL', 'Aflac Inc.', 110.0, 'Financial'],
  ['ALL', 'Allstate Corp.', 165.0, 'Financial'],
  ['TRV', 'Travelers Cos.', 210.0, 'Financial'],
  ['HIG', 'Hartford Financial', 115.0, 'Financial'],
  ['PGR', 'Progressive Corp.', 195.0, 'Financial'],
  ['UNM', 'Unum Group', 52.0, 'Financial'],
  ['LUV', 'Southwest Airlines', 28.0, 'Industrial'],
  ['DAL', 'Delta Air Lines', 48.0, 'Industrial'],
  ['UAL', 'United Airlines', 45.0, 'Industrial'],
  ['AAL', 'American Airlines', 12.0, 'Industrial'],
  ['ALK', 'Alaska Air Group', 42.0, 'Industrial'],
  ['JBLU', 'JetBlue Airways', 5.0, 'Industrial'],
  ['HA', 'Hawaiian Holdings', 14.0, 'Industrial'],
  ['MESA', 'Mesa Air Group', 2.0, 'Industrial'],
  ['SAVE', 'Spirit Airlines', 3.0, 'Industrial'],
  ['ULCC', 'Frontier Group', 5.0, 'Industrial'],
  ['ALGT', 'Allegiant Travel', 55.0, 'Industrial'],
  ['RYAAY', 'Ryanair Holdings', 55.0, 'Industrial'],
  ['CPA', 'Copa Holdings', 90.0, 'Industrial'],
  ['DLTR', 'Dollar Tree', 70.0, 'Consumer'],
  ['DG', 'Dollar General', 80.0, 'Consumer'],
  ['FIVE', 'Five Below', 25.0, 'Consumer'],
  ['BBY', 'Best Buy Co.', 90.0, 'Consumer'],
  ['BBWI', 'Bath & Body Works', 35.0, 'Consumer'],
  ['VFC', 'VF Corp.', 25.0, 'Consumer'],
  ['RL', 'Ralph Lauren', 220.0, 'Consumer'],
  ['TPR', 'Tapestry Inc.', 55.0, 'Consumer'],
  ['NKE', 'Nike Inc.', 78.0, 'Consumer'],
  ['UAA', 'Under Armour', 9.0, 'Consumer'],
  ['LULU', 'Lululemon Athletica', 280.0, 'Consumer'],
  ['PVH', 'PVH Corp.', 100.0, 'Consumer'],
  ['GES', "Guess Inc.", 20.0, 'Consumer'],
  ['ANF', 'Abercrombie & Fitch', 140.0, 'Consumer'],
  ['AEO', 'American Eagle Outfitters', 20.0, 'Consumer'],
  ['URBN', 'Urban Outfitters', 70.0, 'Consumer'],
  ['GPS', 'Gap Inc.', 25.0, 'Consumer'],
  ['ROST', "Ross Stores", 150.0, 'Consumer'],
  ['DG', 'Dollar General', 80.0, 'Consumer'],
  ['DLTR', 'Dollar Tree', 70.0, 'Consumer'],
  ['KSS', "Kohl's Corp.", 18.0, 'Consumer'],
  ['M', "Macy's Inc.", 18.0, 'Consumer'],
  ['JWN', 'Nordstrom Inc.', 22.0, 'Consumer'],
  ['DDS', 'Dillard Inc.', 380.0, 'Consumer'],
  ['SAH', 'Sonic Automotive', 65.0, 'Consumer'],
  ['PAG', 'Penske Automotive', 165.0, 'Consumer'],
  ['ABG', 'Asbury Automotive Group', 230.0, 'Consumer'],
  ['LAD', 'Lithia Motors', 320.0, 'Consumer'],
  ['KMX', 'CarMax Inc.', 75.0, 'Consumer'],
  ['AN', 'AutoNation Inc.', 175.0, 'Consumer'],
  ['GPI', 'Group 1 Automotive', 340.0, 'Consumer'],
  ['SHOO', 'Steven Madden', 42.0, 'Consumer'],
  ['CROX', 'Crocs Inc.', 140.0, 'Consumer'],
  ['DECK', 'Deckers Outdoor', 850.0, 'Consumer'],
  ['SNE', 'Sony Group', 95.0, 'Technology'],
  ['TM', 'Toyota Motor', 185.0, 'Automotive'],
  ['HMC', 'Honda Motor', 25.0, 'Automotive'],
  ['NSANY', 'Nissan Motor', 8.0, 'Automotive'],
  ['SUZUY', 'Suzuki Motor', 20.0, 'Automotive'],
  ['HYMTF', 'Hyundai Motor', 45.0, 'Automotive'],
  ['RACE', 'Ferrari NV', 420.0, 'Automotive'],
  ['STLA', 'Stellantis NV', 15.0, 'Automotive'],
  ['VWAGY', 'Volkswagen AG', 12.0, 'Automotive'],
  ['BMWYY', 'BMW AG', 35.0, 'Automotive'],
  ['MBGYY', 'Mercedes-Benz', 12.0, 'Automotive'],
  ['RIVN', 'Rivian Automotive', 12.0, 'Automotive'],
  ['LCID', 'Lucid Group', 3.0, 'Automotive'],
  ['NIO', 'NIO Inc.', 5.0, 'Automotive'],
  ['LI', 'Li Auto Inc.', 20.0, 'Automotive'],
  ['XPEV', 'XPeng Inc.', 8.0, 'Automotive'],
  ['F', 'Ford Motor', 10.0, 'Automotive'],
  ['GM', 'General Motors', 48.0, 'Automotive'],
  ['STU', 'Stellantis NV', 15.0, 'Automotive'],
  ['PSNY', 'Polestar Automotive', 1.5, 'Automotive'],
  ['FFIE', 'Faraday Future', 1.2, 'Automotive'],
  ['NKLA', 'Nikola Corp.', 0.8, 'Automotive'],
  ['HYZN', 'Hyzon Motors', 1.0, 'Automotive'],
  ['WKHS', 'Workhorse Group', 0.5, 'Automotive'],
  ['ARVL', 'Arrival', 0.3, 'Automotive'],
  ['MULN', 'Mullen Automotive', 0.15, 'Automotive'],
  ['SOLO', 'Electrameccanica', 0.5, 'Automotive'],
  ['GOEV', 'Canoo Inc.', 0.4, 'Automotive'],
  ['LOAR', 'Loar Holdings', 30.0, 'Industrial'],
  ['ASTS', 'AST SpaceMobile', 25.0, 'Technology'],
  ['RKLB', 'Rocket Lab USA', 7.0, 'Industrial'],
  ['SPCE', 'Virgin Galactic', 1.5, 'Industrial'],
  ['JOBY', 'Joby Aviation', 6.0, 'Industrial'],
  ['ACHR', 'Archer Aviation', 4.0, 'Industrial'],
  ['LILM', 'Lilium NV', 0.6, 'Industrial'],
  ['EH', 'EHang Holdings', 12.0, 'Industrial'],
  ['BLDP', 'Ballard Power', 2.0, 'Industrial'],
  ['PLUG', 'Plug Power', 2.0, 'Industrial'],
  ['FCEL', 'FuelCell Energy', 0.5, 'Industrial'],
  ['BE', 'Bloom Energy', 12.0, 'Industrial'],
  ['CHPT', 'ChargePoint Holdings', 1.5, 'Industrial'],
  ['BLNK', 'Blink Charging', 2.0, 'Industrial'],
  ['EVGO', 'EVgo Inc.', 3.0, 'Industrial'],
  ['WBX', 'Wallbox NV', 1.5, 'Industrial'],
  ['QS', 'QuantumScape', 6.0, 'Technology'],
  ['SILA', 'Silicon Ranch', 25.0, 'Utilities'],
  ['ARRY', 'Array Technologies', 18.0, 'Industrial'],
  ['NOVA', 'Sunnova Energy', 5.0, 'Utilities'],
  ['ENPH', 'Enphase Energy', 85.0, 'Technology'],
  ['SEDG', 'SolarEdge Technologies', 25.0, 'Technology'],
  ['FSLR', 'First Solar', 220.0, 'Technology'],
  ['RUN', 'Sunrun Inc.', 15.0, 'Utilities'],
  ['SPWR', 'SunPower Corp.', 3.0, 'Utilities'],
  ['CSIQ', 'Canadian Solar', 18.0, 'Technology'],
  ['JKS', 'JinkoSolar', 25.0, 'Technology'],
  ['DQ', 'Daqo New Energy', 18.0, 'Technology'],
  ['ARRY', 'Array Technologies', 18.0, 'Industrial'],
  ['GNTX', 'Gentex Corp.', 32.0, 'Industrial'],
  ['LEA', 'Lear Corp.', 120.0, 'Consumer'],
  ['BWA', 'BorgWarner', 35.0, 'Industrial'],
  ['ALV', 'Autoliv Inc.', 100.0, 'Consumer'],
  ['MTOR', 'Meritor Inc.', 22.0, 'Industrial'],
  ['AXL', 'American Axle', 8.0, 'Industrial'],
  ['GT', 'Goodyear Tire', 10.0, 'Consumer'],
  ['CTB', 'Cooper Tire', 30.0, 'Consumer'],
  ['SMG', 'Scotts Miracle-Gro', 65.0, 'Materials'],
  ['FMC', 'FMC Corp.', 55.0, 'Materials'],
  ['ALB', 'Albemarle Corp.', 90.0, 'Materials'],
  ['SQM', 'Sociedad Quimica', 45.0, 'Materials'],
  ['LTHM', 'Livent Corp.', 8.0, 'Materials'],
  ['LAC', 'Lithium Americas', 3.0, 'Materials'],
  ['PLL', 'Piedmont Lithium', 8.0, 'Materials'],
  ['SNMN', 'Sigma Lithium', 20.0, 'Materials'],
  ['AMX', 'America Movil', 18.0, 'Technology'],
  ['TIMB', 'TIM Brasil', 18.0, 'Technology'],
  ['TEF', 'Telefonica SA', 4.5, 'Technology'],
  ['TU', 'Telenor ASA', 12.0, 'Technology'],
  ['CHA', 'China Telecom', 25.0, 'Technology'],
  ['CHL', 'China Mobile', 25.0, 'Technology'],
  ['CHA', 'China Unicom', 6.0, 'Technology'],
  ['SKM', 'SK Telecom', 22.0, 'Technology'],
  ['KT', 'KT Corp.', 15.0, 'Technology'],
  ['NTT', 'Nippon Telegraph', 32.0, 'Technology'],
  ['DCM', 'NTT Docomo', 35.0, 'Technology'],
  ['SBH', 'Sally Beauty', 12.0, 'Consumer'],
  ['DG', 'Dollar General', 80.0, 'Consumer'],
  ['DLTR', 'Dollar Tree', 70.0, 'Consumer'],
  ['FIVE', 'Five Below', 25.0, 'Consumer'],
  ['OLLI', "Ollie's Bargain", 85.0, 'Consumer'],
  ['BIG', 'Big Lots', 1.5, 'Consumer'],
  ['KIRK', "Kirkland's Inc.", 2.0, 'Consumer'],
  ['PLCE', "Children's Place", 18.0, 'Consumer'],
  ['GES', "Guess Inc.", 20.0, 'Consumer'],
  ['CRI', 'Carter Inc.', 65.0, 'Consumer'],
  ['PVH', 'PVH Corp.', 100.0, 'Consumer'],
  ['HD', 'Home Depot', 360.0, 'Consumer'],
  ['LOW', "Lowe's Companies", 255.0, 'Consumer'],
  ['SHW', 'Sherwin-Williams', 360.0, 'Materials'],
  ['PPG', 'PPG Industries', 120.0, 'Materials'],
  ['MAS', 'Masco Corp.', 82.0, 'Consumer'],
  ['BLDR', 'Builders FirstSource', 175.0, 'Industrial'],
  ['TREX', 'Trex Company', 65.0, 'Materials'],
  ['FND', 'Floor & Decor', 120.0, 'Consumer'],
  ['LL', 'Lumber Liquidators', 12.0, 'Consumer'],
  ['WHR', 'Whirlpool Corp.', 100.0, 'Consumer'],
  ['LEG', 'Leggett & Platt', 12.0, 'Consumer'],
  ['SNDR', 'Sonida Senior Living', 15.0, 'Healthcare'],
  ['PEAK', 'Healthpeak Properties', 18.0, 'Real Estate'],
  ['O', 'Realty Income', 58.0, 'Real Estate'],
  ['VICI', 'VICI Properties', 32.0, 'Real Estate'],
  ['WPC', 'WP Carey', 60.0, 'Real Estate'],
  ['STAG', 'STAG Industrial', 37.0, 'Real Estate'],
  ['EQR', 'Equity Residential', 68.0, 'Real Estate'],
  ['AVB', 'AvalonBay Communities', 185.0, 'Real Estate'],
  ['MAA', 'Mid-America Apartments', 155.0, 'Real Estate'],
  ['UDR', 'UDR Inc.', 42.0, 'Real Estate'],
  ['CPT', 'Camden Property', 115.0, 'Real Estate'],
  ['ESS', 'Essex Property', 270.0, 'Real Estate'],
  ['EQIX', 'Equinix Inc.', 810.0, 'Real Estate'],
  ['DLR', 'Digital Realty', 160.0, 'Real Estate'],
  ['PSA', 'Public Storage', 115.0, 'Real Estate'],
  ['EXR', 'Extra Space Storage', 160.0, 'Real Estate'],
  ['CUBE', 'CubeSmart', 45.0, 'Real Estate'],
  ['LSI', 'Life Storage Inc.', 145.0, 'Real Estate'],
  ['NSA', 'National Storage', 42.0, 'Real Estate'],
  ['AMT', 'American Tower', 225.0, 'Real Estate'],
  ['CCI', 'Crown Castle', 100.0, 'Real Estate'],
  ['SBAC', 'SBA Communications', 240.0, 'Real Estate'],
  ['WY', 'Weyerhaeuser', 30.0, 'Real Estate'],
  ['RYN', 'Rayonier Inc.', 32.0, 'Real Estate'],
  ['PCH', 'PotlatchDeltic', 42.0, 'Real Estate'],
  ['WFG', 'Weyerhaeuser', 30.0, 'Materials'],
  ['DEL', 'Delta Air Lines', 48.0, 'Industrial'],
  ['AAP', 'Advance Auto Parts', 35.0, 'Consumer'],
  ['ORLY', "O'Reilly Automotive", 480.0, 'Consumer'],
  ['AZO', 'AutoZone Inc.', 3200.0, 'Consumer'],
  ['MNRO', 'Monro Inc.', 42.0, 'Consumer'],
  ['FND', 'Floor & Decor', 120.0, 'Consumer'],
  ['HD', 'Home Depot', 360.0, 'Consumer'],
  ['WDFC', 'WD-40 Co.', 250.0, 'Consumer'],
  ['CLX', 'Clorox Co.', 140.0, 'Consumer'],
  ['CHD', 'Church & Dwight', 105.0, 'Consumer'],
  ['CL', 'Colgate-Palmolive', 95.0, 'Consumer'],
  ['HSY', 'Hershey Co.', 200.0, 'Consumer'],
  ['MKC', 'McCormick & Co.', 78.0, 'Consumer'],
  ['SJM', 'J.M. Smucker', 120.0, 'Consumer'],
  ['CAG', 'Conagra Brands', 30.0, 'Consumer'],
  ['GIS', 'General Mills', 65.0, 'Consumer'],
  ['K', 'Kellogg Co.', 55.0, 'Consumer'],
  ['POST', 'Post Holdings', 110.0, 'Consumer'],
  ['FLO', 'Flowers Foods', 25.0, 'Consumer'],
  ['TSN', 'Tyson Foods', 60.0, 'Consumer'],
  ['PPC', 'Pilgrim Pride', 40.0, 'Consumer'],
  ['SAFM', 'Sanderson Farms', 200.0, 'Consumer'],
  ['HRL', 'Hormel Foods', 30.0, 'Consumer'],
  ['BG', 'Bunge Ltd.', 95.0, 'Materials'],
  ['ADM', 'Archer-Daniels-Midland', 60.0, 'Consumer'],
  ['MDLZ', 'Mondelez Intl', 68.0, 'Consumer'],
  ['STZ', 'Constellation Brands', 245.0, 'Consumer'],
  ['TAP', 'Molson Coors', 55.0, 'Consumer'],
  ['BUD', 'Anheuser-Busch', 55.0, 'Consumer'],
  ['DEO', 'Diageo plc', 105.0, 'Consumer'],
  ['BF.B', 'Brown-Forman', 165.0, 'Consumer'],
  ['WING', 'Wingstop Inc.', 380.0, 'Consumer'],
  ['CMG', 'Chipotle Mexican', 55.0, 'Consumer'],
  ['DPZ', "Domino's Pizza", 480.0, 'Consumer'],
  ['PZZA', "Papa John's Intl", 50.0, 'Consumer'],
  ['JACK', 'Jack in the Box', 45.0, 'Consumer'],
  ['DNUT', 'Krispy Kreme', 12.0, 'Consumer'],
  ['SHAK', 'Shake Shack', 75.0, 'Consumer'],
  ['WEN', "Wendy's Co.", 18.0, 'Consumer'],
  ['BJRI', "BJ's Restaurants", 35.0, 'Consumer'],
  ['DIN', "Dine Brands Global", 45.0, 'Consumer'],
  ['CAKE', 'Cheesecake Factory', 40.0, 'Consumer'],
  ['EAT', 'Brinker Intl', 40.0, 'Consumer'],
  ['BLMN', 'Bloomin Brands', 25.0, 'Consumer'],
  ['DRI', 'Darden Restaurants', 165.0, 'Consumer'],
  ['LW', 'Lamb Weston Holdings', 85.0, 'Consumer'],
  ['PPC', 'Pilgrims Pride', 40.0, 'Consumer'],
  ['TSN', 'Tyson Foods', 60.0, 'Consumer'],
  ['HRL', 'Hormel Foods', 30.0, 'Consumer'],
  ['SYY', 'Sysco Corp.', 78.0, 'Consumer'],
  ['PFGC', 'Performance Food', 75.0, 'Consumer'],
  ['USFD', 'US Foods Holding', 38.0, 'Consumer'],
  ['WMT', 'Walmart Inc.', 78.0, 'Consumer'],
  ['COST', 'Costco Wholesale', 875.0, 'Consumer'],
  ['TGT', 'Target Corp.', 145.0, 'Consumer'],
  ['BJ', "BJ's Wholesale", 80.0, 'Consumer'],
  ['K', 'Kellogg Co.', 55.0, 'Consumer'],
  ['GIS', 'General Mills', 65.0, 'Consumer'],
  ['HSY', 'Hershey Co.', 200.0, 'Consumer'],
  ['NKE', 'Nike Inc.', 78.0, 'Consumer'],
  ['VFC', 'VF Corp.', 25.0, 'Consumer'],
  ['RL', 'Ralph Lauren', 220.0, 'Consumer'],
  ['TPR', 'Tapestry Inc.', 55.0, 'Consumer'],
  ['PVH', 'PVH Corp.', 100.0, 'Consumer'],
  ['HD', 'Home Depot', 360.0, 'Consumer'],
  ['LOW', "Lowe's Companies", 255.0, 'Consumer'],
  ['SHW', 'Sherwin-Williams', 360.0, 'Materials'],
  ['PPG', 'PPG Industries', 120.0, 'Materials'],
  ['NEM', 'Newmont Corp.', 45.0, 'Materials'],
  ['GOLD', 'Barrick Gold', 20.0, 'Materials'],
  ['AEM', 'Agnico Eagle Mines', 65.0, 'Materials'],
  ['KGC', 'Kinross Gold', 9.0, 'Materials'],
  ['ABX', 'Barrick Gold', 20.0, 'Materials'],
  ['GDX', 'VanEck Gold Miners', 40.0, 'Materials'],
  ['AA', 'Alcoa Corp.', 40.0, 'Materials'],
  ['CENX', 'Century Aluminum', 18.0, 'Materials'],
  ['NUE', 'Nucor Corp.', 170.0, 'Materials'],
  ['STLD', 'Steel Dynamics', 135.0, 'Materials'],
  ['X', 'United States Steel', 35.0, 'Materials'],
  ['CLF', 'Cleveland-Cliffs', 15.0, 'Materials'],
  ['ATI', 'ATI Inc.', 55.0, 'Materials'],
  ['CRS', 'Carpenter Technology', 55.0, 'Materials'],
  ['TKR', 'Timken Co.', 40.0, 'Industrial'],
  ['DOV', 'Dover Corp.', 180.0, 'Industrial'],
  ['ETN', 'Eaton Corp.', 340.0, 'Industrial'],
  ['EMR', 'Emerson Electric', 125.0, 'Industrial'],
  ['ITW', 'Illinois Tool Works', 260.0, 'Industrial'],
  ['ROK', 'Rockwell Automation', 280.0, 'Industrial'],
  ['PNR', 'Pentair plc', 105.0, 'Industrial'],
  ['MMM', '3M Co.', 130.0, 'Industrial'],
  ['GE', 'General Electric', 175.0, 'Industrial'],
  ['HON', 'Honeywell International', 205.0, 'Industrial'],
  ['LMT', 'Lockheed Martin', 460.0, 'Industrial'],
  ['NOC', 'Northrop Grumman', 480.0, 'Industrial'],
  ['RTX', 'RTX Corp.', 120.0, 'Industrial'],
  ['GD', 'General Dynamics', 300.0, 'Industrial'],
  ['TXT', 'Textron Inc.', 45.0, 'Industrial'],
  ['HII', 'Huntington Ingalls', 230.0, 'Industrial'],
  ['CW', 'Curtiss-Wright Corp.', 360.0, 'Industrial'],
  ['HEI', 'HEICO Corp.', 220.0, 'Industrial'],
  ['TDG', 'TransDigm Group', 1300.0, 'Industrial'],
  ['AME', 'AMETEK Inc.', 170.0, 'Industrial'],
  ['XYL', 'Xylem Inc.', 60.0, 'Industrial'],
  ['PNR', 'Pentair plc', 105.0, 'Industrial'],
  ['SPXC', 'SPX Technologies', 85.0, 'Industrial'],
  ['FLS', 'Flowserve Corp.', 40.0, 'Industrial'],
  ['B', 'Barnes Group', 22.0, 'Industrial'],
  ['CR', 'Crane Co.', 150.0, 'Industrial'],
  ['ITT', 'ITT Inc.', 135.0, 'Industrial'],
  ['IR', 'Ingersoll Rand', 95.0, 'Industrial'],
  ['GGG', 'Graco Inc.', 85.0, 'Industrial'],
  ['NDSN', 'Nordson Corp.', 260.0, 'Industrial'],
  ['AVY', 'Avery Dennison', 200.0, 'Materials'],
  ['PKG', 'Packaging Corp.', 180.0, 'Materials'],
  ['IP', 'International Paper', 55.0, 'Materials'],
  ['SEE', 'Sealed Air Corp.', 38.0, 'Materials'],
  ['CCK', 'Crown Holdings', 90.0, 'Materials'],
  ['BALL', 'Ball Corp.', 60.0, 'Materials'],
  ['SON', 'Sonoco Products', 55.0, 'Materials'],
  ['GPK', 'Graphic Packaging', 25.0, 'Materials'],
  ['WRK', 'WestRock Co.', 40.0, 'Materials'],
  ['IPG', 'Interpublic Group', 35.0, 'Consumer'],
  ['OMC', 'Omnicom Group', 95.0, 'Consumer'],
  ['PUB', 'Publicis Groupe', 60.0, 'Consumer'],
  ['WPP', 'WPP plc', 50.0, 'Consumer'],
  ['NCMI', 'National CineMedia', 2.0, 'Consumer'],
  ['CNK', 'Cinemark Holdings', 22.0, 'Consumer'],
  ['AMC', 'AMC Entertainment', 5.0, 'Consumer'],
  ['CNW', 'Cinemark Holdings', 22.0, 'Consumer'],
  ['DIS', 'Walt Disney Co.', 92.0, 'Consumer'],
  ['NFLX', 'Netflix Inc.', 690.0, 'Technology'],
  ['CMCSA', 'Comcast Corp.', 42.0, 'Technology'],
  ['T', 'AT&T Inc.', 22.0, 'Technology'],
  ['VZ', 'Verizon Comm.', 42.0, 'Technology'],
  ['CHTR', 'Charter Comm.', 350.0, 'Technology'],
  ['TMUS', 'T-Mobile US', 200.0, 'Technology'],
  ['DISH', 'Dish Network', 5.0, 'Technology'],
  ['SATS', 'EchoStar Corp.', 25.0, 'Technology'],
  ['IRDM', 'Iridium Comm.', 32.0, 'Technology'],
  ['VSAT', 'Viasat Inc.', 25.0, 'Technology'],
  ['SPCE', 'Virgin Galactic', 1.5, 'Industrial'],
  ['ASTS', 'AST SpaceMobile', 25.0, 'Technology'],
  ['GSAT', 'Globalstar Inc.', 1.5, 'Technology'],
  ['RKLB', 'Rocket Lab USA', 7.0, 'Industrial'],
];

const CRYPTO_DATA: Array<[string, string, number]> = [
  ['BTC', 'Bitcoin', 64000],
  ['ETH', 'Ethereum', 2600],
  ['BNB', 'BNB', 580],
  ['SOL', 'Solana', 145],
  ['XRP', 'XRP', 0.58],
  ['ADA', 'Cardano', 0.35],
  ['DOGE', 'Dogecoin', 0.10],
  ['TRX', 'TRON', 0.15],
  ['TON', 'Toncoin', 5.2],
  ['AVAX', 'Avalanche', 25],
  ['SHIB', 'Shiba Inu', 0.000018],
  ['DOT', 'Polkadot', 4.2],
  ['LINK', 'Chainlink', 11],
  ['MATIC', 'Polygon', 0.42],
  ['BCH', 'Bitcoin Cash', 350],
  ['NEAR', 'NEAR Protocol', 4.5],
  ['LTC', 'Litecoin', 65],
  ['UNI', 'Uniswap', 7.5],
  ['ICP', 'Internet Computer', 12],
  ['APT', 'Aptos', 8.5],
  ['XLM', 'Stellar', 0.10],
  ['ETC', 'Ethereum Classic', 22],
  ['FIL', 'Filecoin', 4.5],
  ['HBAR', 'Hedera', 0.06],
  ['VET', 'VeChain', 0.022],
  ['ARB', 'Arbitrum', 0.55],
  ['OP', 'Optimism', 1.5],
  ['MKR', 'Maker', 2200],
  ['AAVE', 'Aave', 95],
  ['GRT', 'The Graph', 0.18],
  ['ALGO', 'Algorand', 0.12],
  ['ATOM', 'Cosmos', 4.5],
  ['STX', 'Stacks', 1.5],
  ['XTZ', 'Tezos', 0.65],
  ['THETA', 'Theta Network', 1.2],
  ['IMX', 'Immutable', 1.2],
  ['RUNE', 'THORChain', 4.5],
  ['SUI', 'Sui', 1.0],
  ['SEI', 'Sei', 0.35],
  ['TIA', 'Celestia', 6.5],
  ['INJ', 'Injective', 22],
  ['FLOW', 'Flow', 0.65],
  ['GALA', 'Gala', 0.025],
  ['CHZ', 'Chiliz', 0.06],
  ['SAND', 'The Sandbox', 0.28],
  ['MANA', 'Decentraland', 0.30],
  ['AXS', 'Axie Infinity', 5.5],
  ['CRV', 'Curve DAO', 0.25],
  ['PEPE', 'Pepe', 0.0000085],
  ['WIF', 'dogwifhat', 1.8],
  ['BONK', 'Bonk', 0.000022],
  ['FLOKI', 'FLOKI', 0.00015],
  ['JUP', 'Jupiter', 0.75],
  ['PYTH', 'Pyth Network', 0.35],
  ['DYDX', 'dYdX', 1.2],
  ['GMX', 'GMX', 28],
  ['COMP', 'Compound', 48],
  ['SNX', 'Synthetix', 2.2],
  ['1INCH', '1inch', 0.35],
  ['BAL', 'Balancer', 2.5],
  ['YFI', 'Yearn Finance', 5500],
  ['SUSHI', 'SushiSwap', 0.65],
  ['CVX', 'Convex Finance', 22],
  ['FXS', 'Frax Share', 2.5],
  ['LDO', 'Lido DAO', 1.5],
  ['ENS', 'Ethereum Name Service', 22],
  ['BLUR', 'Blur', 0.15],
  ['LOOKS', 'LooksRare', 0.08],
  ['RARE', 'SuperRare', 0.12],
  ['WLD', 'Worldcoin', 1.8],
  ['DYM', 'Dymension', 1.5],
  ['MANTA', 'Manta Network', 0.65],
  ['ALT', 'Altlayer', 0.12],
  ['MNT', 'Mantle', 0.55],
  ['STRK', 'Starknet', 0.45],
  ['JTO', 'Jito', 2.5],
  ['RNDR', 'Render', 7.5],
  ['FET', 'Fetch.ai', 1.2],
  ['AGIX', 'SingularityNET', 0.45],
  ['OCEAN', 'Ocean Protocol', 0.55],
  ['CTSI', 'Cartesi', 0.15],
  ['NMR', 'Numeraire', 12],
  ['OXT', 'Orchid', 0.08],
  ['ANKR', 'Ankr', 0.035],
  ['CHRL', 'Chiliz', 0.06],
  ['GAS', 'Gas', 3.5],
  ['LSK', 'Lisk', 1.2],
  ['WAVES', 'Waves', 1.5],
  ['KSM', 'Kusama', 22],
  ['QTUM', 'Qtum', 2.8],
  ['ZIL', 'Zilliqa', 0.018],
  ['KAVA', 'Kava', 0.45],
  ['ROSE', 'Oasis Network', 0.06],
  ['CELO', 'Celo', 0.65],
  ['MINA', 'Mina Protocol', 0.55],
  ['IOTA', 'IOTA', 0.15],
  ['EOS', 'EOS', 0.65],
  ['XEC', 'eCash', 0.000028],
  ['XMR', 'Monero', 145],
  ['DASH', 'Dash', 22],
  ['ZEC', 'Zcash', 22],
  ['KAS', 'Kaspa', 0.15],
  ['ORDI', 'ORDI', 28],
  ['SATS', 'SATS', 0.00035],
  ['RATS', 'RATS', 0.00015],
  ['MUB', 'MUB', 0.08],
  ['SOLR', 'SolRazr', 0.12],
  ['JUP', 'Jupiter', 0.75],
  ['PYTH', 'Pyth Network', 0.35],
  ['WEN', 'Wen', 0.00012],
  ['NFP', 'NFPrompt', 0.25],
  ['JUP', 'Jupiter', 0.75],
  ['ORCA', 'Orca', 3.2],
  ['HNT', 'Helium', 6.5],
  ['MOBILE', 'Helium Mobile', 0.005],
  ['IOTX', 'IoTeX', 0.025],
  ['KLAY', 'Klaytn', 0.15],
  ['WEMIX', 'WEMIX', 1.2],
  ['CFX', 'Conflux', 0.18],
  ['MASK', 'Mask Network', 2.5],
  ['COCOS', 'Cocos-BCX', 0.018],
  ['BTCST', 'BTC Standard Hashrate', 0.15],
  ['LUNA', 'Terra Classic', 0.00008],
  ['LUNC', 'Terra Luna Classic', 0.00008],
  ['USTC', 'TerraClassicUSD', 0.015],
  ['BSC', 'Binance Coin', 580],
  ['TUSD', 'TrueUSD', 1.0],
  ['USDC', 'USD Coin', 1.0],
  ['DAI', 'Dai', 1.0],
  ['FRAX', 'Frax', 0.98],
  ['USDD', 'Decentralized USD', 1.0],
  ['USDT', 'Tether', 1.0],
  ['PAXG', 'Pax Gold', 2400],
  ['XAUT', 'Tether Gold', 2400],
  ['WBTC', 'Wrapped Bitcoin', 64000],
  ['STETH', 'Lido Staked ETH', 2600],
  ['CBETH', 'Coinbase Staked ETH', 2700],
  ['RETH', 'Rocket Pool ETH', 2800],
  ['BETH', 'Binance Staked ETH', 2600],
  ['ANKR', 'Ankr', 0.035],
  ['POLYX', 'Polymesh', 0.18],
  ['XPL', 'PlanetWatch', 0.015],
  ['ASTO', 'Altered State', 0.05],
  ['QNT', 'Quant', 65],
  ['XDC', 'XDC Network', 0.028],
  ['XRD', 'Radix', 0.035],
  ['ASTR', 'Astar', 0.065],
  ['GLMR', 'Moonbeam', 0.25],
  ['MOVR', 'Moonriver', 6.5],
  ['EQ', 'Equilibrium', 0.005],
  ['ZRX', '0x Protocol', 0.45],
  ['BNT', 'Bancor', 0.45],
  ['KNC', 'Kyber Network', 0.65],
  ['LRC', 'Loopring', 0.18],
  ['REP', 'Augur', 0.85],
  ['DNT', 'district0x', 0.015],
  ['POWR', 'Power Ledger', 0.15],
  ['MTL', 'Metal', 1.5],
  ['SNT', 'Status', 0.025],
  ['RPL', 'Rocket Pool', 12],
  ['NEXO', 'Nexo', 1.2],
  ['CEL', 'Celsius', 0.15],
  ['HT', 'Huobi Token', 0.25],
  ['OKB', 'OKB', 45],
  ['LEO', 'UNUS SED LEO', 9.5],
  ['CRO', 'Cronos', 0.08],
  ['KCS', 'KuCoin Shares', 8.5],
  ['BGB', 'Bitget Token', 1.2],
  ['FTT', 'FTX Token', 1.5],
  ['SRM', 'Serum', 0.25],
  ['RAY', 'Raydium', 1.5],
  ['STEP', 'Step Finance', 0.12],
  ['SLND', 'Solend', 0.65],
  ['TULIP', 'Tulip', 3.5],
  ['SBR', 'Saber', 0.015],
  ['ORCA', 'Orca', 3.2],
  ['STEP', 'Step Finance', 0.12],
  ['ATLAS', 'Star Atlas', 0.005],
  ['POLIS', 'Star Atlas DAO', 0.08],
  ['AURY', 'Aurory', 1.2],
  ['FIDA', 'Bonfida', 0.25],
  ['COPE', 'Cope', 0.15],
  ['MAPS', 'Maps', 0.25],
  ['SLIM', 'Solanium', 0.08],
  ['LIKE', 'Only1', 0.025],
  ['WOBSOUL', 'Wobo', 0.005],
  ['SLND', 'Solend', 0.65],
  ['PORT', 'Port Finance', 0.08],
  ['FRKT', 'Frukost', 0.015],
  ['GHO', 'Ghost', 0.005],
  ['MNDE', 'Marinade', 0.12],
  ['JITO', 'Jito', 2.5],
  ['HNT', 'Helium', 6.5],
  ['MNTL', 'Asset Mantle', 0.012],
  ['DSM', 'Desmos', 0.05],
  ['BAND', 'Band Protocol', 1.2],
  ['DIA', 'Dia', 0.35],
  ['API3', 'API3', 1.5],
  ['TRB', 'Tellor', 12],
  ['NEST', 'Nest Protocol', 0.015],
  ['DOS', 'DOS Network', 0.005],
  ['LINK', 'Chainlink', 11],
  ['BAND', 'Band Protocol', 1.2],
  ['PYTH', 'Pyth Network', 0.35],
  ['API3', 'API3', 1.5],
  ['UMA', 'UMA', 2.5],
  ['KEEP', 'Keep Network', 0.25],
  ['NU', 'NuCypher', 0.05],
  ['RNDR', 'Render', 7.5],
  ['FET', 'Fetch.ai', 1.2],
  ['AGIX', 'SingularityNET', 0.45],
  ['OCEAN', 'Ocean Protocol', 0.55],
  ['CTSI', 'Cartesi', 0.15],
  ['NMR', 'Numeraire', 12],
  ['OXT', 'Orchid', 0.08],
  ['ANKR', 'Ankr', 0.035],
  ['CHRL', 'Chiliz', 0.06],
  ['GAS', 'Gas', 3.5],
  ['LSK', 'Lisk', 1.2],
  ['WAVES', 'Waves', 1.5],
  ['KSM', 'Kusama', 22],
  ['QTUM', 'Qtum', 2.8],
  ['ZIL', 'Zilliqa', 0.018],
  ['KAVA', 'Kava', 0.45],
  ['ROSE', 'Oasis Network', 0.06],
  ['CELO', 'Celo', 0.65],
  ['MINA', 'Mina Protocol', 0.55],
  ['IOTA', 'IOTA', 0.15],
  ['EOS', 'EOS', 0.65],
  ['XEC', 'eCash', 0.000028],
  ['XMR', 'Monero', 145],
  ['DASH', 'Dash', 22],
  ['ZEC', 'Zcash', 22],
  ['KAS', 'Kaspa', 0.15],
  ['ORDI', 'ORDI', 28],
  ['SATS', 'SATS', 0.00035],
  ['RATS', 'RATS', 0.00015],
  ['MUB', 'MUB', 0.08],
  ['SOLR', 'SolRazr', 0.12],
  ['JUP', 'Jupiter', 0.75],
  ['PYTH', 'Pyth Network', 0.35],
  ['WEN', 'Wen', 0.00012],
  ['NFP', 'NFPrompt', 0.25],
  ['JUP', 'Jupiter', 0.75],
  ['ORCA', 'Orca', 3.2],
  ['HNT', 'Helium', 6.5],
  ['MOBILE', 'Helium Mobile', 0.005],
  ['IOTX', 'IoTeX', 0.025],
  ['KLAY', 'Klaytn', 0.15],
  ['WEMIX', 'WEMIX', 1.2],
  ['CFX', 'Conflux', 0.18],
  ['MASK', 'Mask Network', 2.5],
  ['COCOS', 'Cocos-BCX', 0.018],
  ['BTCST', 'BTC Standard Hashrate', 0.15],
  ['LUNA', 'Terra Classic', 0.00008],
  ['LUNC', 'Terra Luna Classic', 0.00008],
  ['USTC', 'TerraClassicUSD', 0.015],
  ['BSC', 'Binance Coin', 580],
  ['TUSD', 'TrueUSD', 1.0],
  ['USDC', 'USD Coin', 1.0],
  ['DAI', 'Dai', 1.0],
  ['FRAX', 'Frax', 0.98],
  ['USDD', 'Decentralized USD', 1.0],
  ['USDT', 'Tether', 1.0],
  ['PAXG', 'Pax Gold', 2400],
  ['XAUT', 'Tether Gold', 2400],
  ['WBTC', 'Wrapped Bitcoin', 64000],
  ['STETH', 'Lido Staked ETH', 2600],
  ['CBETH', 'Coinbase Staked ETH', 2700],
  ['RETH', 'Rocket Pool ETH', 2800],
  ['BETH', 'Binance Staked ETH', 2600],
  ['ANKR', 'Ankr', 0.035],
  ['POLYX', 'Polymesh', 0.18],
  ['XPL', 'PlanetWatch', 0.015],
  ['ASTO', 'Altered State', 0.05],
  ['QNT', 'Quant', 65],
  ['XDC', 'XDC Network', 0.028],
  ['XRD', 'Radix', 0.035],
  ['ASTR', 'Astar', 0.065],
  ['GLMR', 'Moonbeam', 0.25],
  ['MOVR', 'Moonriver', 6.5],
  ['EQ', 'Equilibrium', 0.005],
  ['ZRX', '0x Protocol', 0.45],
  ['BNT', 'Bancor', 0.45],
  ['KNC', 'Kyber Network', 0.65],
  ['LRC', 'Loopring', 0.18],
  ['REP', 'Augur', 0.85],
  ['DNT', 'district0x', 0.015],
  ['POWR', 'Power Ledger', 0.15],
  ['MTL', 'Metal', 1.5],
  ['SNT', 'Status', 0.025],
  ['RPL', 'Rocket Pool', 12],
  ['NEXO', 'Nexo', 1.2],
  ['CEL', 'Celsius', 0.15],
  ['HT', 'Huobi Token', 0.25],
  ['OKB', 'OKB', 45],
  ['LEO', 'UNUS SED LEO', 9.5],
  ['CRO', 'Cronos', 0.08],
  ['KCS', 'KuCoin Shares', 8.5],
  ['BGB', 'Bitget Token', 1.2],
  ['FTT', 'FTX Token', 1.5],
  ['SRM', 'Serum', 0.25],
  ['RAY', 'Raydium', 1.5],
  ['STEP', 'Step Finance', 0.12],
  ['SLND', 'Solend', 0.65],
  ['TULIP', 'Tulip', 3.5],
  ['SBR', 'Saber', 0.015],
  ['ORCA', 'Orca', 3.2],
  ['STEP', 'Step Finance', 0.12],
  ['ATLAS', 'Star Atlas', 0.005],
  ['POLIS', 'Star Atlas DAO', 0.08],
  ['AURY', 'Aurory', 1.2],
  ['FIDA', 'Bonfida', 0.25],
  ['COPE', 'Cope', 0.15],
  ['MAPS', 'Maps', 0.25],
  ['SLIM', 'Solanium', 0.08],
  ['LIKE', 'Only1', 0.025],
  ['WOBSOUL', 'Wobo', 0.005],
  ['SLND', 'Solend', 0.65],
  ['PORT', 'Port Finance', 0.08],
  ['FRKT', 'Frukost', 0.015],
  ['GHO', 'Ghost', 0.005],
  ['MNDE', 'Marinade', 0.12],
  ['JITO', 'Jito', 2.5],
  ['HNT', 'Helium', 6.5],
  ['MNTL', 'Asset Mantle', 0.012],
  ['DSM', 'Desmos', 0.05],
  ['BAND', 'Band Protocol', 1.2],
  ['DIA', 'Dia', 0.35],
  ['API3', 'API3', 1.5],
  ['TRB', 'Tellor', 12],
  ['NEST', 'Nest Protocol', 0.015],
  ['DOS', 'DOS Network', 0.005],
  ['LINK', 'Chainlink', 11],
  ['BAND', 'Band Protocol', 1.2],
  ['PYTH', 'Pyth Network', 0.35],
  ['API3', 'API3', 1.5],
  ['UMA', 'UMA', 2.5],
  ['KEEP', 'Keep Network', 0.25],
  ['NU', 'NuCypher', 0.05],
  ['RNDR', 'Render', 7.5],
  ['FET', 'Fetch.ai', 1.2],
  ['AGIX', 'SingularityNET', 0.45],
  ['OCEAN', 'Ocean Protocol', 0.55],
  ['CTSI', 'Cartesi', 0.15],
  ['NMR', 'Numeraire', 12],
  ['OXT', 'Orchid', 0.08],
  ['ANKR', 'Ankr', 0.035],
  ['CHRL', 'Chiliz', 0.06],
  ['GAS', 'Gas', 3.5],
  ['LSK', 'Lisk', 1.2],
  ['WAVES', 'Waves', 1.5],
  ['KSM', 'Kusama', 22],
  ['QTUM', 'Qtum', 2.8],
  ['ZIL', 'Zilliqa', 0.018],
  ['KAVA', 'Kava', 0.45],
  ['ROSE', 'Oasis Network', 0.06],
  ['CELO', 'Celo', 0.65],
  ['MINA', 'Mina Protocol', 0.55],
  ['IOTA', 'IOTA', 0.15],
  ['EOS', 'EOS', 0.65],
  ['XEC', 'eCash', 0.000028],
  ['XMR', 'Monero', 145],
  ['DASH', 'Dash', 22],
  ['ZEC', 'Zcash', 22],
  ['KAS', 'Kaspa', 0.15],
  ['ORDI', 'ORDI', 28],
  ['SATS', 'SATS', 0.00035],
  ['RATS', 'RATS', 0.00015],
  ['MUB', 'MUB', 0.08],
  ['SOLR', 'SolRazr', 0.12],
  ['JUP', 'Jupiter', 0.75],
  ['PYTH', 'Pyth Network', 0.35],
  ['WEN', 'Wen', 0.00012],
  ['NFP', 'NFPrompt', 0.25],
  ['JUP', 'Jupiter', 0.75],
  ['ORCA', 'Orca', 3.2],
  ['HNT', 'Helium', 6.5],
  ['MOBILE', 'Helium Mobile', 0.005],
  ['IOTX', 'IoTeX', 0.025],
  ['KLAY', 'Klaytn', 0.15],
  ['WEMIX', 'WEMIX', 1.2],
  ['CFX', 'Conflux', 0.18],
  ['MASK', 'Mask Network', 2.5],
  ['COCOS', 'Cocos-BCX', 0.018],
  ['BTCST', 'BTC Standard Hashrate', 0.15],
  ['LUNA', 'Terra Classic', 0.00008],
  ['LUNC', 'Terra Luna Classic', 0.00008],
  ['USTC', 'TerraClassicUSD', 0.015],
  ['BSC', 'Binance Coin', 580],
  ['TUSD', 'TrueUSD', 1.0],
  ['USDC', 'USD Coin', 1.0],
  ['DAI', 'Dai', 1.0],
  ['FRAX', 'Frax', 0.98],
  ['USDD', 'Decentralized USD', 1.0],
  ['USDT', 'Tether', 1.0],
  ['PAXG', 'Pax Gold', 2400],
  ['XAUT', 'Tether Gold', 2400],
  ['WBTC', 'Wrapped Bitcoin', 64000],
  ['STETH', 'Lido Staked ETH', 2600],
  ['CBETH', 'Coinbase Staked ETH', 2700],
  ['RETH', 'Rocket Pool ETH', 2800],
  ['BETH', 'Binance Staked ETH', 2600],
  ['ANKR', 'Ankr', 0.035],
  ['POLYX', 'Polymesh', 0.18],
  ['XPL', 'PlanetWatch', 0.015],
  ['ASTO', 'Altered State', 0.05],
  ['QNT', 'Quant', 65],
  ['XDC', 'XDC Network', 0.028],
  ['XRD', 'Radix', 0.035],
  ['ASTR', 'Astar', 0.065],
  ['GLMR', 'Moonbeam', 0.25],
  ['MOVR', 'Moonriver', 6.5],
  ['EQ', 'Equilibrium', 0.005],
  ['ZRX', '0x Protocol', 0.45],
  ['BNT', 'Bancor', 0.45],
  ['KNC', 'Kyber Network', 0.65],
  ['LRC', 'Loopring', 0.18],
  ['REP', 'Augur', 0.85],
  ['DNT', 'district0x', 0.015],
  ['POWR', 'Power Ledger', 0.15],
  ['MTL', 'Metal', 1.5],
  ['SNT', 'Status', 0.025],
  ['RPL', 'Rocket Pool', 12],
  ['NEXO', 'Nexo', 1.2],
  ['CEL', 'Celsius', 0.15],
  ['HT', 'Huobi Token', 0.25],
  ['OKB', 'OKB', 45],
  ['LEO', 'UNUS SED LEO', 9.5],
  ['CRO', 'Cronos', 0.08],
  ['KCS', 'KuCoin Shares', 8.5],
  ['BGB', 'Bitget Token', 1.2],
  ['FTT', 'FTX Token', 1.5],
  ['SRM', 'Serum', 0.25],
  ['RAY', 'Raydium', 1.5],
  ['STEP', 'Step Finance', 0.12],
  ['SLND', 'Solend', 0.65],
  ['TULIP', 'Tulip', 3.5],
  ['SBR', 'Saber', 0.015],
  ['ORCA', 'Orca', 3.2],
  ['STEP', 'Step Finance', 0.12],
  ['ATLAS', 'Star Atlas', 0.005],
  ['POLIS', 'Star Atlas DAO', 0.08],
  ['AURY', 'Aurory', 1.2],
  ['FIDA', 'Bonfida', 0.25],
  ['COPE', 'Cope', 0.15],
  ['MAPS', 'Maps', 0.25],
  ['SLIM', 'Solanium', 0.08],
  ['LIKE', 'Only1', 0.025],
  ['WOBSOUL', 'Wobo', 0.005],
  ['SLND', 'Solend', 0.65],
  ['PORT', 'Port Finance', 0.08],
  ['FRKT', 'Frukost', 0.015],
  ['GHO', 'Ghost', 0.005],
  ['MNDE', 'Marinade', 0.12],
  ['JITO', 'Jito', 2.5],
  ['HNT', 'Helium', 6.5],
  ['MNTL', 'Asset Mantle', 0.012],
  ['DSM', 'Desmos', 0.05],
  ['BAND', 'Band Protocol', 1.2],
  ['DIA', 'Dia', 0.35],
  ['API3', 'API3', 1.5],
  ['TRB', 'Tellor', 12],
  ['NEST', 'Nest Protocol', 0.015],
  ['DOS', 'DOS Network', 0.005],
  ['LINK', 'Chainlink', 11],
  ['BAND', 'Band Protocol', 1.2],
  ['PYTH', 'Pyth Network', 0.35],
  ['API3', 'API3', 1.5],
  ['UMA', 'UMA', 2.5],
  ['KEEP', 'Keep Network', 0.25],
  ['NU', 'NuCypher', 0.05],
  ['RNDR', 'Render', 7.5],
  ['FET', 'Fetch.ai', 1.2],
  ['AGIX', 'SingularityNET', 0.45],
  ['OCEAN', 'Ocean Protocol', 0.55],
  ['CTSI', 'Cartesi', 0.15],
  ['NMR', 'Numeraire', 12],
  ['OXT', 'Orchid', 0.08],
  ['ANKR', 'Ankr', 0.035],
  ['CHRL', 'Chiliz', 0.06],
  ['GAS', 'Gas', 3.5],
  ['LSK', 'Lisk', 1.2],
  ['WAVES', 'Waves', 1.5],
  ['KSM', 'Kusama', 22],
  ['QTUM', 'Qtum', 2.8],
  ['ZIL', 'Zilliqa', 0.018],
  ['KAVA', 'Kava', 0.45],
  ['ROSE', 'Oasis Network', 0.06],
  ['CELO', 'Celo', 0.65],
  ['MINA', 'Mina Protocol', 0.55],
  ['IOTA', 'IOTA', 0.15],
  ['EOS', 'EOS', 0.65],
  ['XEC', 'eCash', 0.000028],
  ['XMR', 'Monero', 145],
  ['DASH', 'Dash', 22],
  ['ZEC', 'Zcash', 22],
  ['KAS', 'Kaspa', 0.15],
  ['ORDI', 'ORDI', 28],
  ['SATS', 'SATS', 0.00035],
  ['RATS', 'RATS', 0.00015],
  ['MUB', 'MUB', 0.08],
  ['SOLR', 'SolRazr', 0.12],
  ['JUP', 'Jupiter', 0.75],
  ['PYTH', 'Pyth Network', 0.35],
  ['WEN', 'Wen', 0.00012],
  ['NFP', 'NFPrompt', 0.25],
  ['JUP', 'Jupiter', 0.75],
  ['ORCA', 'Orca', 3.2],
  ['HNT', 'Helium', 6.5],
  ['MOBILE', 'Helium Mobile', 0.005],
  ['IOTX', 'IoTeX', 0.025],
  ['KLAY', 'Klaytn', 0.15],
  ['WEMIX', 'WEMIX', 1.2],
  ['CFX', 'Conflux', 0.18],
  ['MASK', 'Mask Network', 2.5],
  ['COCOS', 'Cocos-BCX', 0.018],
  ['BTCST', 'BTC Standard Hashrate', 0.15],
  ['LUNA', 'Terra Classic', 0.00008],
  ['LUNC', 'Terra Luna Classic', 0.00008],
  ['USTC', 'TerraClassicUSD', 0.015],
  ['BSC', 'Binance Coin', 580],
  ['TUSD', 'TrueUSD', 1.0],
  ['USDC', 'USD Coin', 1.0],
  ['DAI', 'Dai', 1.0],
  ['FRAX', 'Frax', 0.98],
  ['USDD', 'Decentralized USD', 1.0],
  ['USDT', 'Tether', 1.0],
  ['PAXG', 'Pax Gold', 2400],
  ['XAUT', 'Tether Gold', 2400],
  ['WBTC', 'Wrapped Bitcoin', 64000],
  ['STETH', 'Lido Staked ETH', 2600],
  ['CBETH', 'Coinbase Staked ETH', 2700],
  ['RETH', 'Rocket Pool ETH', 2800],
  ['BETH', 'Binance Staked ETH', 2600],
  ['ANKR', 'Ankr', 0.035],
  ['POLYX', 'Polymesh', 0.18],
  ['XPL', 'PlanetWatch', 0.015],
  ['ASTO', 'Altered State', 0.05],
  ['QNT', 'Quant', 65],
  ['XDC', 'XDC Network', 0.028],
  ['XRD', 'Radix', 0.035],
  ['ASTR', 'Astar', 0.065],
  ['GLMR', 'Moonbeam', 0.25],
  ['MOVR', 'Moonriver', 6.5],
  ['EQ', 'Equilibrium', 0.005],
  ['ZRX', '0x Protocol', 0.45],
  ['BNT', 'Bancor', 0.45],
  ['KNC', 'Kyber Network', 0.65],
  ['LRC', 'Loopring', 0.18],
  ['REP', 'Augur', 0.85],
  ['DNT', 'district0x', 0.015],
  ['POWR', 'Power Ledger', 0.15],
  ['MTL', 'Metal', 1.5],
  ['SNT', 'Status', 0.025],
  ['RPL', 'Rocket Pool', 12],
  ['NEXO', 'Nexo', 1.2],
  ['CEL', 'Celsius', 0.15],
  ['HT', 'Huobi Token', 0.25],
  ['OKB', 'OKB', 45],
  ['LEO', 'UNUS SED LEO', 9.5],
  ['CRO', 'Cronos', 0.08],
  ['KCS', 'KuCoin Shares', 8.5],
  ['BGB', 'Bitget Token', 1.2],
  ['FTT', 'FTX Token', 1.5],
  ['SRM', 'Serum', 0.25],
  ['RAY', 'Raydium', 1.5],
  ['STEP', 'Step Finance', 0.12],
  ['SLND', 'Solend', 0.65],
  ['TULIP', 'Tulip', 3.5],
  ['SBR', 'Saber', 0.015],
  ['ORCA', 'Orca', 3.2],
  ['STEP', 'Step Finance', 0.12],
  ['ATLAS', 'Star Atlas', 0.005],
  ['POLIS', 'Star Atlas DAO', 0.08],
  ['AURY', 'Aurory', 1.2],
  ['FIDA', 'Bonfida', 0.25],
  ['COPE', 'Cope', 0.15],
  ['MAPS', 'Maps', 0.25],
  ['SLIM', 'Solanium', 0.08],
  ['LIKE', 'Only1', 0.025],
  ['WOBSOUL', 'Wobo', 0.005],
  ['SLND', 'Solend', 0.65],
  ['PORT', 'Port Finance', 0.08],
  ['FRKT', 'Frukost', 0.015],
  ['GHO', 'Ghost', 0.005],
  ['MNDE', 'Marinade', 0.12],
  ['JITO', 'Jito', 2.5],
  ['HNT', 'Helium', 6.5],
  ['MNTL', 'Asset Mantle', 0.012],
  ['DSM', 'Desmos', 0.05],
  ['BAND', 'Band Protocol', 1.2],
  ['DIA', 'Dia', 0.35],
  ['API3', 'API3', 1.5],
  ['TRB', 'Tellor', 12],
  ['NEST', 'Nest Protocol', 0.015],
  ['DOS', 'DOS Network', 0.005],
  ['LINK', 'Chainlink', 11],
  ['BAND', 'Band Protocol', 1.2],
  ['PYTH', 'Pyth Network', 0.35],
  ['API3', 'API3', 1.5],
  ['UMA', 'UMA', 2.5],
  ['KEEP', 'Keep Network', 0.25],
  ['NU', 'NuCypher', 0.05],
];

function buildAssets(): Asset[] {
  const assets: Asset[] = [];
  const seenSymbols = new Set<string>();

  STOCK_DATA.forEach((row, idx) => {
    const [symbol, name, basePrice, sector] = row;
    const key = `stock-${symbol}`;
    if (seenSymbols.has(key)) return;
    seenSymbols.add(key);
    const rng = seededRandom(idx * 1000 + 1);
    const changePercent = (rng() - 0.45) * 8;
    const change = (basePrice * changePercent) / 100;
    const volume = Math.floor(rng() * 50_000_000) + 1_000_000;
    const marketCap = basePrice * (Math.floor(rng() * 5_000_000_000) + 100_000_000);
    const history = generateHistory(basePrice, idx * 1000 + 1);
    assets.push({
      symbol,
      name,
      price: Math.round((basePrice + change) * 100) / 100,
      change: Math.round(change * 100) / 100,
      changePercent: Math.round(changePercent * 100) / 100,
      volume,
      marketCap,
      type: 'stock',
      sector,
      history,
    });
  });

  CRYPTO_DATA.forEach((row, idx) => {
    const [symbol, name, basePrice] = row;
    const key = `crypto-${symbol}`;
    if (seenSymbols.has(key)) return;
    seenSymbols.add(key);
    const rng = seededRandom((idx + 500) * 1000 + 1);
    const changePercent = (rng() - 0.45) * 12;
    const change = (basePrice * changePercent) / 100;
    const volume = Math.floor(rng() * 10_000_000_000) + 100_000_000;
    const marketCap = basePrice * (Math.floor(rng() * 500_000_000) + 10_000_000);
    const history = generateHistory(basePrice, (idx + 500) * 1000 + 1);
    assets.push({
      symbol,
      name,
      price: Math.round((basePrice + change) * 1000000) / 1000000,
      change: Math.round(change * 1000000) / 1000000,
      changePercent: Math.round(changePercent * 100) / 100,
      volume,
      marketCap,
      type: 'crypto',
      history,
    });
  });

  return assets;
}

let cachedAssets: Asset[] | null = null;

export function getAllAssets(): Asset[] {
  if (!cachedAssets) {
    cachedAssets = buildAssets();
  }
  return cachedAssets;
}

export function getStocks(): Asset[] {
  return getAllAssets().filter((a) => a.type === 'stock');
}

export function getCrypto(): Asset[] {
  return getAllAssets().filter((a) => a.type === 'crypto');
}

export function getTopGainers(count = 10): Asset[] {
  return [...getAllAssets()].sort((a, b) => b.changePercent - a.changePercent).slice(0, count);
}

export function getTopLosers(count = 10): Asset[] {
  return [...getAllAssets()].sort((a, b) => a.changePercent - a.changePercent).slice(0, count);
}

export function getMostActive(count = 10): Asset[] {
  return [...getAllAssets()].sort((a, b) => b.volume - a.volume).slice(0, count);
}

export function getAssetBySymbol(symbol: string): Asset | undefined {
  return getAllAssets().find((a) => a.symbol === symbol);
}

export function formatCurrency(value: number): string {
  if (value >= 1_000_000_000_000) return `$${(value / 1_000_000_000_000).toFixed(2)}T`;
  if (value >= 1_000_000_000) return `$${(value / 1_000_000_000).toFixed(2)}B`;
  if (value >= 1_000_000) return `$${(value / 1_000_000).toFixed(2)}M`;
  if (value >= 1_000) return `$${(value / 1_000).toFixed(2)}K`;
  return `$${value.toFixed(2)}`;
}

export function formatPrice(value: number): string {
  if (value < 0.01) return `$${value.toFixed(8)}`;
  if (value < 1) return `$${value.toFixed(4)}`;
  return `$${value.toFixed(2)}`;
}

export function formatVolume(value: number): string {
  if (value >= 1_000_000_000) return `${(value / 1_000_000_000).toFixed(2)}B`;
  if (value >= 1_000_000) return `${(value / 1_000_000).toFixed(2)}M`;
  if (value >= 1_000) return `${(value / 1_000).toFixed(2)}K`;
  return value.toString();
}
